services:
  database:
    build: ./database
    env_file:
      - .env
    volumes:
      - db-data:/data/db
    networks:
      - backend-net
  backend:
    build: ./backend
    env_file:
      - .env
    networks:
      - backend-net
      - frontend-net
    depends_on:
      - database
  frontend:
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend-net
    depends_on:
      - backend
volumes:
  db-data:
networks:
  backend-net:
  frontend-net:
