services:
  database:
    image: mongo:8.0
    volumes:
      - db-data:/data/db
    env_file:
      - ./backend/.env
    networks:
      - backend-net
      # - frontend-net
  backend:
    build: ./backend
    ports:
      - 8000:8000
    networks:
      - backend-net
    env_file:
      - ./backend/.env
    depends_on:
      - database
volumes:
  db-data:
networks:
  backend-net: # frontend-net:
